### ISSUE TITLE
Find new names for the "Controller" and "Rules" component

### ISSUE THREAD

**Issue by deviantony** [deviantony/docker-CRN#32]

**Comment by deviantony** [comment]
Propositions for "Controller":
- factory

**Comment by deviantony** [comment]
Propositions for "Rules":
- central-core

(from http://terminator.wikia.com/wiki/Skynet)

**Comment by rems** [comment]
Deal for central-core

For the controller, I suggest "terminator-genisys" (like the movie to be released by early July), as it both terminates and generates instances

**Comment by deviantony** [comment]
Deal for "genisys", we don't need to include terminator everywhere ;)

![toomuchterminator](http://rs2img.memecdn.com/very-creative_o_2647411.webp)
